### ISSUE TITLE
generating a wallet doesn't seem to work

### ISSUE THREAD

**Issue by iateadonut** [filidorwiese/stellar-wallet#1]
i have tried (with a different address than the one below) and tried to send 20.0001 XLM and was unable.

here is the output when i attempted to generate another address

stellar-wallet-cli generate

Stellar Wallet Generate Wallet

  Public address: GBCEVJOEGRRQD4B74GVOCN7PN7OADWIYEL43KHUD52ER5EZYXFKQTQOB

  Print this wallet and make sure to store it somewhere safe! 

  Note: You need to put at least 20XLM on this key for it to be an active account 

 ~ $ stellar-wallet-cli balance

Stellar Wallet Balance Check

? Enter wallet address: GBCEVJOEGRRQD4B74GVOCN7PN7OADWIYEL43KHUD52ER5EZYXFKQTQOB

NotFoundError

**Comment by filidorwiese** [comment]
For a stellar address to be active, you need to at least have 20XLM in it. After generating a wallet, make a 20XLM payment to it (for example, from another wallet or exchange). Then check the balance again!

**Comment by iateadonut** [comment]
yeah, it worked when i sent from lobstr.  it didn't work from poloniex so that must have been on them.  (their outgoing transactions for XLM are even 'temporarily' disabled now)

(crazy how fast these transactions are)
