### ISSUE TITLE
Error: Not Found

### ISSUE THREAD

**Issue by rudijs** [filidorwiese/stellar-wallet#16]
Hi,

Am seeing this error today, everything was working fine in the past.

Not sure how to debug this one?

```
node -v
v10.15.3

npm -g list | grep stell
└─┬ stellar-wallet-cli@1.1.3
  └─┬ stellar-sdk@0.13.0
    ├─┬ stellar-base@0.11.0

```

```
stellar-wallet-cli pay
-----------------------------------------------
Stellar Wallet Make Payment
----------------------------------------------- 

? Enter XLM amount to send: 5
? Enter destination address: GC**********
? Enter memo (optional): 
? Enter sender secret: SA*******

Error: Not Found
```

**Comment by filidorwiese** [comment]
Hi, thanks for your bug report. I've just tested a payment and experienced no problems. It might have been a network related issue. Could you try again?

**Comment by rudijs** [comment]
Hi @filidorwiese 

Yep all good now.

I just tried again, same steps as previously, and it went right through.

As you suggested probably a network issue.

I'm a huge fan of this npm module and use it often - really appreciate your time and efforts on this :-)

Thanks again.
